language: node_js

sudo: false

branches:
  only:
  - master

node_js:
  - "6"

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_972fb1949e7c_key -iv $encrypted_972fb1949e7c_iv -in .travis/travis.ssh.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name 'Yiang Guo'
  - git config --global user.email 'contact@guoyiang.com'

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo g -d